/*---{CHALLANGE}-------------------------------------------------------------------------------------------------------
ENTREGA DEVOPS TOOLS & CLOUD COMPUTING

GRUPO TILLS
RM93042 - FILIPE SANTOS DA SILVA
RM94467 - FRANKLIN PEREIRA DO NASCIMENTO
RM92920 - JOSE GABRIEL DA SILVA COELHO
RM94141 - MARIANA NIETON BORGES
RM93915 - JAELSON JONAS DOS SANTOS

----------------------------------------------------------------------------------------------------------------------------*/

/*---{COMANDOS DML }--------------------------------------------------------------------------------------------------------*/

DROP TABLE T_CAN_BOT CASCADE CONSTRAINTS;

DROP TABLE T_CAN_CANTEIRO CASCADE CONSTRAINTS;

DROP TABLE T_CAN_ENTRADA_USUARIO CASCADE CONSTRAINTS;

DROP TABLE T_CAN_INTERACAO CASCADE CONSTRAINTS;

DROP TABLE T_CAN_LOGIN CASCADE CONSTRAINTS;

DROP TABLE T_CAN_PLANTAS CASCADE CONSTRAINTS;

DROP TABLE T_CAN_PLANTIO CASCADE CONSTRAINTS;

DROP TABLE T_CAN_RESPOSTA_BOT CASCADE CONSTRAINTS;

DROP TABLE T_CAN_USUARIO CASCADE CONSTRAINTS;

DROP TABLE T_CAN_LOG CASCADE CONSTRAINTS;

CREATE TABLE T_CAN_BOT (
    ID_BOT       NUMBER NOT NULL,
    DS_NOME_BOT  VARCHAR2(50) NOT NULL,
    DS_VERSAO    VARCHAR2(10) NOT NULL
)
;

COMMENT ON COLUMN T_CAN_BOT.ID_BOT IS
    'ESTE CAMPO E A CHAVE PRIMARIA E ARMAZENARA O ID DO BOT.
';

COMMENT ON COLUMN T_CAN_BOT.DS_NOME_BOT IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA O NOME DA VERSÃƑO DO BOT.';

COMMENT ON COLUMN T_CAN_BOT.DS_VERSAO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA A VERSÃƑO DO BOT.';

ALTER TABLE T_CAN_BOT ADD CONSTRAINT T_CAN_BOT_PK PRIMARY KEY ( ID_BOT );

CREATE TABLE T_CAN_CANTEIRO (
    ID_CANTEIRO  NUMBER(5) NOT NULL,
    ID_USUARIO   NUMBER(10),
    NM_CANTEIRO  VARCHAR2(100) NOT NULL,
    DT_CRIACAO   DATE NOT NULL
)
;

COMMENT ON COLUMN T_CAN_CANTEIRO.ID_CANTEIRO IS
    'CHAVE PRIMARIA, ARMAZENA O ID DO CANTEIRO';

COMMENT ON COLUMN T_CAN_CANTEIRO.NM_CANTEIRO IS
    'OBRIGATORIO, ARMAZENA O NOME DO CANTEIRO DO USUARIO';

COMMENT ON COLUMN T_CAN_CANTEIRO.DT_CRIACAO IS
    'OBRIGATORIO, ARMAZENA A DATA DE CRIACAO DO CANTEIRO';

ALTER TABLE T_CAN_CANTEIRO ADD CONSTRAINT T_CAN_CANTEIRO_PK PRIMARY KEY ( ID_CANTEIRO );

CREATE TABLE T_CAN_ENTRADA_USUARIO (
    ID_MENSAGEM_USUARIO  NUMBER(5) NOT NULL,
    ID_INTERACAO         NUMBER(5) NOT NULL,
    DS_MENSAGEM          VARCHAR2(1000) NOT NULL,
    DT_ENVIO             DATE NOT NULL
)
;

COMMENT ON COLUMN T_CAN_ENTRADA_USUARIO.ID_MENSAGEM_USUARIO IS
    'ESTE CAMPO E A CHAVE PRIMARIA E ARMAZENARA O ID DAS MENSAGEN DO USUARIO';

COMMENT ON COLUMN T_CAN_ENTRADA_USUARIO.DS_MENSAGEM IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENARA A MENSAGEM DO USUARIO.';

COMMENT ON COLUMN T_CAN_ENTRADA_USUARIO.DT_ENVIO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENARA A DATA E HORA DO ENVIO DA MENSAGEM.';

ALTER TABLE T_CAN_ENTRADA_USUARIO ADD CONSTRAINT T_CAN_ENTRADA_USUARIO_PK PRIMARY KEY ( ID_MENSAGEM_USUARIO );

CREATE TABLE T_CAN_INTERACAO (
    ID_INTERACAO  NUMBER(5) NOT NULL,
    ID_USUARIO    NUMBER(10) NOT NULL,
    ID_BOT        NUMBER NOT NULL,
    ID_CONTEXTO   NUMBER(5) NOT NULL,
    DS_ASSUNTO    VARCHAR2(100) NOT NULL,
    DT_INTERACAO  DATE NOT NULL
)
;

COMMENT ON COLUMN T_CAN_INTERACAO.ID_INTERACAO IS
    'ESTE CAMPO E A CHAVE PRIMARIA E ARMAZENARA O ID DA INTERAÃ‡ÃƑO.';

COMMENT ON COLUMN T_CAN_INTERACAO.ID_CONTEXTO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENARA O CONTEXTO DA INTERAÃ‡ÃƑO.';

COMMENT ON COLUMN T_CAN_INTERACAO.DS_ASSUNTO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA O ASSUNTO DA CONVERSA BASEADO NA PRIMEIRA MENSAGEM ENVIADA PARA O BOT.';

COMMENT ON COLUMN T_CAN_INTERACAO.DT_INTERACAO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA A DATA DA INTERAÃ‡ÃƑO.';

CREATE UNIQUE INDEX T_CAN_INTERACAO__IDX ON
    T_CAN_INTERACAO (ID_BOT);

ALTER TABLE T_CAN_INTERACAO ADD CONSTRAINT T_CAN_INTERACAO_PK PRIMARY KEY ( ID_INTERACAO );

CREATE TABLE T_CAN_LOGIN (
    ID_LOGIN  NUMBER(10) NOT NULL,
    DS_EMAIL  VARCHAR2(100) NOT NULL,
    DS_SENHA  VARCHAR2(100) NOT NULL
)
;

COMMENT ON COLUMN T_CAN_LOGIN.ID_LOGIN IS
    'GUARDA O ID DO LOGIN DO USUARIO. ESTE CAMPO E A CHAVE PRIMARIA.';

COMMENT ON COLUMN T_CAN_LOGIN.DS_EMAIL IS
    'ESTE CAMPO E OBRIGATORIO E GUARDA O E-MAIL DO USUARIO.';

COMMENT ON COLUMN T_CAN_LOGIN.DS_SENHA IS
    'ESTE CAMPO E OBRIGATORIO E GUARDA A SENHA DO USUARIO.';

ALTER TABLE T_CAN_LOGIN ADD CONSTRAINT T_CAN_LOGIN_PK PRIMARY KEY ( ID_LOGIN );

ALTER TABLE T_CAN_LOGIN ADD CONSTRAINT T_CAN_LOGIN_DS_EMAIL_UN UNIQUE ( DS_EMAIL );

CREATE TABLE T_CAN_PLANTAS (
    ID_PLANTA      NUMBER(5) NOT NULL,
    NM_PLANTA      VARCHAR2(100) NOT NULL,
    NR_REGACAO     NUMBER(2) NOT NULL,
    NM_CIENTIFICO  VARCHAR2(100),
    NM_APELIDO     VARCHAR2(100)
)
;

COMMENT ON COLUMN T_CAN_PLANTAS.ID_PLANTA IS
    'CHAVE PRIMARIA, ARMAZENA O ID DAS PLANTAS';

COMMENT ON COLUMN T_CAN_PLANTAS.NM_PLANTA IS
    'OBRIGATORIO, ARMAZENA O NOME DA PLANTA';

COMMENT ON COLUMN T_CAN_PLANTAS.NR_REGACAO IS
    'OBRIGATORIO, ARMAZENA A QUANTIDADE DE VEZES QUE A PLANTA DEVE SER REGADA POR DIA
';

COMMENT ON COLUMN T_CAN_PLANTAS.NM_CIENTIFICO IS
    'OPCIONAL, ARMAZENA O NOME CIENTIFICO DA PLANTA';

COMMENT ON COLUMN T_CAN_PLANTAS.NM_APELIDO IS
    'OPCIONAL, ARMAZENA O APELIDO DA PLANTA';

ALTER TABLE T_CAN_PLANTAS ADD CONSTRAINT T_CAN_PLANTAS_PK PRIMARY KEY ( ID_PLANTA );

CREATE TABLE T_CAN_PLANTIO (
    ID_PLANTIO   NUMBER(5) NOT NULL,
    ID_PLANTA    NUMBER(5) NOT NULL,
    ID_CANTEIRO  NUMBER(5) NOT NULL,
    QT_PLANTADA  NUMBER(3) NOT NULL,
    DT_PLANTIO   DATE NOT NULL,
    DT_COLHEITA  DATE
)
;

COMMENT ON COLUMN T_CAN_PLANTIO.ID_PLANTIO IS
    'CHAVE PRIMARIA, ARMAZENA O ID DO PLANTIO';

COMMENT ON COLUMN T_CAN_PLANTIO.QT_PLANTADA IS
    'OBRIGATORIO, ARMAZENA A QUANTIDADE QUE FOI PLANTADA';

COMMENT ON COLUMN T_CAN_PLANTIO.DT_PLANTIO IS
    'OBRIGATORIO, ARMAZENA A DATA DO PLANTIO';

COMMENT ON COLUMN T_CAN_PLANTIO.DT_COLHEITA IS
    'OPCIONAL, ARMAZENA A DATA DA COLHEITA
';

ALTER TABLE T_CAN_PLANTIO ADD CONSTRAINT T_CAN_PLANTIO_PK PRIMARY KEY ( ID_PLANTIO );

CREATE TABLE T_CAN_RESPOSTA_BOT (
    ID_RESPOSTA_BOT  NUMBER(5) NOT NULL,
    ID_INTERACAO     NUMBER(5) NOT NULL,
    DS_MENSAGEM      VARCHAR2(1000) NOT NULL,
    DT_RESPOSTA      DATE NOT NULL
)
;

COMMENT ON COLUMN T_CAN_RESPOSTA_BOT.ID_RESPOSTA_BOT IS
    'ESTE CAMPO E A CHAVE PRIMARIA E ARMAZENARA O ID DAS RESPOSTAS DO BOT.';

COMMENT ON COLUMN T_CAN_RESPOSTA_BOT.DS_MENSAGEM IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENARA A RESPOSTA DO BOT.';

COMMENT ON COLUMN T_CAN_RESPOSTA_BOT.DT_RESPOSTA IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENARA A DATA E HORA DO ENVIO DA RESPOSTA.';

ALTER TABLE T_CAN_RESPOSTA_BOT ADD CONSTRAINT T_CAN_RESPOSTA_BOT_PK PRIMARY KEY ( ID_RESPOSTA_BOT );

CREATE TABLE T_CAN_USUARIO (
    ID_USUARIO     NUMBER(10) NOT NULL,
    ID_LOGIN       NUMBER(10) NOT NULL,
    NM_USUARIO     VARCHAR2(200) NOT NULL,
    DS_CPF         VARCHAR2(11) NOT NULL,
    DT_NASCIMENTO  DATE NOT NULL,
    DS_TELEFONE    VARCHAR2(11) NOT NULL
)
;

COMMENT ON COLUMN T_CAN_USUARIO.ID_USUARIO IS
    'ESTE CAMPO E A CHAVE PRIMARIA E ARMAZENA O ID DE CADASTRO DO USUARIO.';

COMMENT ON COLUMN T_CAN_USUARIO.NM_USUARIO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA O NOME DO USUARIO.';

COMMENT ON COLUMN T_CAN_USUARIO.DS_CPF IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA O CPF DO USUARIO.';

COMMENT ON COLUMN T_CAN_USUARIO.DT_NASCIMENTO IS
    'ESTE CAMPO E OBRIGATORIO E ARMAZENA A DATA DE NASCIMENTO DO USUARIO.';

COMMENT ON COLUMN T_CAN_USUARIO.DS_TELEFONE IS
    'ESTE CAMPO E OBRIGATORIO O TELEFONEDO USUARIO.';

ALTER TABLE T_CAN_USUARIO ADD CONSTRAINT T_CAN_USUARIO_PK PRIMARY KEY ( ID_USUARIO );

ALTER TABLE T_CAN_RESPOSTA_BOT
    ADD CONSTRAINT BOT_INTERACAO_FK FOREIGN KEY ( ID_INTERACAO )
        REFERENCES T_CAN_INTERACAO ( ID_INTERACAO )
    ;

ALTER TABLE T_CAN_PLANTIO
    ADD CONSTRAINT CANTEIRO_PLANTIO_FK FOREIGN KEY ( ID_CANTEIRO )
        REFERENCES T_CAN_CANTEIRO ( ID_CANTEIRO )
    ;

ALTER TABLE T_CAN_INTERACAO
    ADD CONSTRAINT INTERACAO_BOT_FK FOREIGN KEY ( ID_BOT )
        REFERENCES T_CAN_BOT ( ID_BOT )
    ;

ALTER TABLE T_CAN_INTERACAO
    ADD CONSTRAINT INTERACAO_USUARIO_FK FOREIGN KEY ( ID_USUARIO )
        REFERENCES T_CAN_USUARIO ( ID_USUARIO )
    ;

ALTER TABLE T_CAN_PLANTIO
    ADD CONSTRAINT PLANTAS_PLANTIO_FK FOREIGN KEY ( ID_PLANTA )
        REFERENCES T_CAN_PLANTAS ( ID_PLANTA )
    ;

ALTER TABLE T_CAN_CANTEIRO
    ADD CONSTRAINT USUARIO_CANTEIRO_FK FOREIGN KEY ( ID_USUARIO )
        REFERENCES T_CAN_USUARIO ( ID_USUARIO )
    ;

ALTER TABLE T_CAN_ENTRADA_USUARIO
    ADD CONSTRAINT USUARIO_INTERACAO_FK FOREIGN KEY ( ID_INTERACAO )
        REFERENCES T_CAN_INTERACAO ( ID_INTERACAO )
    ;

ALTER TABLE T_CAN_USUARIO
    ADD CONSTRAINT USUARIO_LOGIN_FK FOREIGN KEY ( ID_LOGIN )
        REFERENCES T_CAN_LOGIN ( ID_LOGIN )
    ;